apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: c0rvvz/jenkins-controller-jcasc
        ports:
        - containerPort: 8080
        env:
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/casc.yaml
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-casc-config
          mountPath: /var/jenkins_home/casc.yaml
          subPath: casc.yaml
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: jenkins-casc-config
        configMap:
          name: jenkins-casc-config
